### ISSUE TITLE
trying

### ISSUE THREAD

**Issue by augustot2** [arjuntherajeev/chatbot_template#1]
I'm trying to do a chatbot. I already can make it work in a terminal, but I would like to develop it in a web front end. I do not know much about web development, so what I would like to know is if it is possible to do something like my code below, but in `flask`.

Here the user asks the bot to show a Painter art, by giving it's name and having the artist's name, it displays all its art names and after been chosen, it displays in screen.

    user_input = " "
    while TRUE:
      response = send_message(user_input, context)
      if response['intents'] and response['intents'][0]['intent'] == "user_paint":
        user_input = input(">> ")
        response = send_message(user_input, context)
        context = response['context']
        painter = response['entities']['entity' == "painter_name"]['value']

        # print bot response
        if response['output']['text']:
            print(response['output']['text'][0])

        # get paint description
        user_input = input(">> ")
        response = send_message(user_input, context)
        context = response['context']
        if response['output']['text']:
            print(response['output']['text'][0])
        art_name = response['entities']['entity' == "art_name"]['value']
        show_data(painter_name, paint)

      # Prompt for next round of input.
      user_input = input('>> ')

I'm having trouble thinking how I can make a "wait user input" function like `input()` in `flask-socketio`.

**Comment by arjuntherajeev** [comment]
Hey @augustot2, 

I think I understand what you mean. When we are using Watson Conversation, we make API calls to the given endpoint. The context is passed in the JSON data while making a POST request. 

Anyways, we actually mimic the real-time aspect using AJAX. This can be seen in the file `/static/javascript/chat.js`. This gives you the freedom to wait for user input, pass it to Watson Conversation, get a response and display it to the user without refreshing the page. 

This example does not use any sockets. Now, you can also use the concept of sockets here by running a socket server behind-the-scenes. But, I think that this is not required. 

In the end, both these techniques allow the user to input a message and get a response. Just reiterating that Watson Conversation simply works using API calls. 

Since you mentioned that you are new to web development, I recommend that you clone this repository and run this program locally. You just need to pass in your Watson Conversation Service Credentials (username, password and workspace_ID). 

I hope this answers your question! Feel free to let me know if you need any other help!

**Comment by augustot2** [comment]
Hi, 
I've already cloned and run your code locally, it works, really nice frontend ! But since I do not have a web development background I understand very little the Js code.

**Comment by arjuntherajeev** [comment]
Hi @augustot2, 

Thanks for trying it out! Web Development is easy and fun! Let me try to help you with the JavaScript here:

For this code, we are using plain JavaScript (also called Vanilla JavaScript) and a famous JavaScript library called jQuery. We will look at the file `/static/javascript/chat.js`: 

1. This is an event-handler which listens for the press of the `[ENTER]` button. When we press the `[ENTER`] button, we will invoke 2 functions called `newMessage()` and `newReply()`.
```
$(window).on('keydown', function (e) {
    if (e.which == 13) {
        newMessage();
        newReply();
        return false;
    }
});
```
2. This is also an event-handler. It listens for the click of a button defined with the _class_ `submit` (defined in HTML). It will also invoke the 2 functions - `newMessage()` and `newReply()`. 
```
$('.submit').click(function () {
    newMessage();
    newReply();
});
```
3. This function constructs the new message to be sent. First it gets the message from user input using `$(".message-input input").val()`. Then we simply construct the HTML code like the user icon, message and animation. Finally, we create an AJAX request to the URL `/send_message` and pass the message with the URL. When it is done, the response is received as the variable `e`. This response is then passed as a parameter to the function `newReply()`. 
```
function newMessage() {
    message = $(".message-input input").val();
    if ($.trim(message) == '') {
        return false;
    }
    $('<li class="sent"><img src="http://emilcarlsson.se/assets/mikeross.png" alt="" /><p>' + message + '</p></li>').appendTo($('.messages ul'));
    $('.message-input input').val(null);
    $('.contact.active .preview').html('<span>You: </span>' + message);
    $(".messages").animate({ scrollTop: $(document).height() }, "fast");
    $.ajax({
    url: "/send_message/"+message,
    //data: {'messag':messag,'context':context}
}).done(function(e) {
    newReply(e);
});
};
```
4. This function simply constructs the reply by dynamically generating the necessary HTML. It creates an `li` element and places the user icon and message received from Watson Conversation inside it. This is appended to the `ul` in the HTML. Then, we clear the user input and scroll the window accordingly. Now, the user is ready to input a new message!  
```
function newReply(message) {
    if ($.trim(message) == '') {
        return false;
    }
    $('<li class="replies"><img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" /><p>' + message + '</p></li>').appendTo($('.messages ul'));
    $('.message-input input').val(null);
    $('.contact.active .preview').html('<span>You: </span>' + message);
    $(".messages").animate({ scrollTop: $(document).height() }, "fast");
};
```

**Comment by augustot2** [comment]
Oh, thanks for the Java Script explanation but, how can I "wait" for the input message ?

Every time a message is sent to python server, it activate the "send_message(message)" function, but how can I wait for a new message   while storing the Entities ?

**Comment by arjuntherajeev** [comment]
I think what you mean is something like a traditional chat application where you will keep polling for a message. Like I mentioned, Watson Conversation using the Watson Developer Cloud Python SDK doesn't work this way. It simply makes API calls. 

If you want to actually wait, then you need to write Python code to enable this. I recommend that you read this [article](http://blog.oddbit.com/2013/11/23/long-polling-with-ja/). It uses very similar technology i.e., Python and JavaScript.

Hope this helps!
